name: Dev Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: StalinidzeCorp/ycr-push@main
        env:
          KEY_JSON: ${{secrets.KEY_JSON}}
          REGISTRY_ID: ${{secrets.REGISTRY_ID}}
          DOCKERFILE_PATH: ./Dockerfile.prod
          IMAGE_NAME: telehoot-front
          IMAGE_TAG: latest